#!/bin/sh
# shellcheck disable=SC2046

restart() {
	kill -$(($1 + 34)) $(pidof sb)
}

case $1 in
0|"music")       restart 0  ;;
1|"cputemp")     restart 1  ;;
2|"cpu")         restart 2  ;;
3|"memory")      restart 3  ;;
4|"battery")     restart 4  ;;
5|"wifi")        restart 5  ;;
6|"netspeed")    restart 6  ;;
7|"localip")     restart 7  ;;
8|"publicip")    restart 8  ;;
9|"volume")      restart 9  ;;
10|"mic")        restart 10 ;;
11|"news")       restart 11 ;;
12|"weather")    restart 12 ;;
13|"daypercent") restart 13 ;;
14|"date")       restart 14 ;;
15|"time")       restart 15 ;;
esac
